project:
  type: book

book:
  title: "**Behind the toxic cocktail** - Toxicokinetic mechanisms of pesticide mixture interactions in earthworms"
  subtitle: "Git repository"
  author:
    - name: "Lisa Gollot"
      orcid: ""
      affiliations:
        - name: "Université Paris-Saclay, INRAE, AgroParisTech, UMR 1402 ECOSYS"
          department: "Sol&Tox"
        - name: "Ineris"
          department: "TEAM"
  date: "6/25/2024"
  chapters:
    - index.qmd
    - quarto/A_Earthworm_culture.qmd
    - part: quarto/B_TK_single/B_TK_EPX_IMD.qmd
      chapters:
        - quarto/B_TK_single/B0_TK_MM.qmd
        - quarto/B_TK_single/BA_TK_IMD.qmd
        - quarto/B_TK_single/BA_TK_EPX_1comp.qmd
        - quarto/B_TK_single/BA_TK_EPX_1comp15.qmd
        - quarto/B_TK_single/BB_TK_EPX_2comp.qmd
        - quarto/B_TK_single/BC_TK_EPX_2comp15.qmd
        - quarto/B_TK_single/BD_TK_EPX_2comp30.qmd
    - part: quarto/C_TK_mix/C_TK_mix.qmd
      chapters: 
         - quarto/C_TK_mix/CA_TK_mix_protocole.qmd
         - quarto/C_TK_mix/CB_TK_mix_predictions.qmd
    - quarto/references.qmd
  navbar:
    right:
      - icon: github
        href: https://github.com/LisaGllt/Ew-Growth-IdVar

bibliography: references/references.bib # ne pas exporter toute la bibliothèse juste la collection PhD
csl: references/apa.csl
execute:
  cache: true
  freeze: auto
execute-dir: project
format:
  html:
    code-fold: true
    code-tools: true
    code-block-bg: true
    highlight-style: appearance/lightnord.theme
    code-block-border-left: "#E5E9F0"
    code-overflow: wrap
    code-annotations: select
    theme:
      - cosmo
      - appearance/html_css.scss

editor: 
    markdown:
      canonical: true

