{
  "hash": "db3e49036ce98fde70e32b3d65e1765b",
  "result": {
    "engine": "knitr",
    "markdown": "\n\n\n\n\n# Materiel & Methods\n\n**Research question:** What is the kinetic of uptake and elimination of EPX and IMD in earthworms ?\n\n**Hypothese:** Differences in physicochemical properties—epoxiconazole being more lipophilic and imidacloprid more hydrophilic—are expected to produce distinct toxicokinetic profiles and to result in greater bioaccumulation of epoxiconazole.\n\n**Prediction:** Under co-exposure, the presence of epoxiconazole is expected to reduce the elimination rate of imidacloprid, resulting in higher tissue concentrations of this compound.\n\n## Laboratory experiment\n\n### Exposition of earthworms\n\nA first toxicokinetic experiment (hereafter referred to as “TK”) was conducted following an adapted OECD Test Guideline 317 protocol (OECD, 2010) with destructive sampling to determine uptake and elimination rates of each pesticide in earthworms. The experimental design consisted of two sequential phases: a 21-day uptake phase where earthworms were exposed to pesticide-spiked soil, followed by a 21-day elimination phase where individuals were transferred to control soil for depuration.\n\nSampling was conducted at eight timepoints during each phase: days 1, 2, 3, 7, 10, 14, 17, and 21 for uptake, and days 22, 23, 24, 28, 31, 35, 38, and 42 for elimination (@fig-TKdesign). Each replicate consisted of a single adult earthworm maintained in an individual plastic vessel (11 cm × 7.7 cm × 4.5 cm) containing 200 g dry weight of soil adjusted to 70% water holding capacity. This design enabled individual-level measurements of both growth and internal concentrations throughout the experiment. Organisms were fed 3 g dry weight of horse dung per individual every 14 days and maintained at 18°C in a temperature-controlled environment. Individual body weights were recorded at exposure initiation and at respective sampling timepoints. At each timepoint, four individual earthworms were starved for approximately 24 hours on wet filter paper in Petri dishes to clear gut contents, then weighted and sacrificed to be stored at -80°C for subsequent chemical analysis. When the 24 hours were not enough to clear gut content, individuals were massaged to clear the remaining of the gut content.\n\nTest concentrations were set at 100 ng/g for imidacloprid and 1000 ng/g for epoxiconazole, selected to avoid acute toxicity while ensuring analytical quantifiability. These concentrations represent environmentally relevant exposure levels, approximating maximum concentrations reported in French agricultural soils (Pelosi et al., 2021), providing an optimal balance between analytical detectability and ecological relevance.\n\nA first analysis of the toxicokinetics revealed very rapid uptake and elimination for epoxiconazole, highlighting the potential for bias introduced by the depuration phase in Petri dishes. To address this issue and improve the estimation of uptake and elimination rates, an additional experiment (hereafter referred to as “TK BIS”) to allow for a better estimation of the uptake and elimination rate . It was performed on the same principle as the first one to better estimate the bioaccumulation factor of both pesticides. However, after exposure, earthworms were not starved in Petri dishes but directly massaged to clear their gut content before being stored at -80°C for subsequent chemical analysis. Sampling was performed at 3 time points per pesticide in 3 replicates : 0.25, 1 and 3 days for epoxiconazole and 3, 7 and 14 days for imidacloprid.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt_elim <- 21\nt <- seq(0,t_elim*2,0.1)\nC0 <- 0\nC_soil <- 10\nC_soil <- 1000\nks <- 3\nke <- 0.3\n\nfdata <- function(t, state, parameters) {\n    with(as.list(c(state, parameters)), {\n      if(t<21){dl <- ks*C_soil-ke*state[1]}else{dl <- -ke*state[1]}\n      list(c(dl))\n    })  }\n\n# Initial condition\ninit_var <- c(C0)\n\n# Parameters and time\nparams <- c(\n  ks=ks, \n  ke=ke, \n  C_soil=C_soil\n  )\n\n# Resolution\nsol_fdata <- ode(\n  y=init_var, \n  times=t, \n  func=fdata, \n  parms=params\n  )\n  \nsim_data_ex <- data.frame(\n  t= sol_fdata[,1], \n  Cworm = sol_fdata[,2]\n  )\nsim_data_ex_up <- sim_data_ex[sim_data_ex$t<=t_elim,]\nsim_data_ex_elim <- sim_data_ex[sim_data_ex$t>=t_elim,]\n\ntimes_uptake <- c(1, 2, 3, 7, 10, 14, 17, 21)\ntimes_elim <- c(22, 23, 24, 28, 31, 35, 38, 42)\ntimes_points <- c(times_uptake, times_elim)\n\nsim_data_points <- sim_data_ex[sim_data_ex$t %in% times_points,]\n\n\np <- ggplot()+\n  geom_line(\n    aes(\n      x=sim_data_ex_up$t, \n      y=sim_data_ex_up$Cworm\n      ), \n    color=col_uptake, \n    linewidth=2\n    )+\n  geom_line(\n    aes(\n      x=sim_data_ex_elim$t, \n      y=sim_data_ex_elim$Cworm\n      ), \n    color=col_elim, \n    linewidth=2\n    )+\n  geom_point(\n    aes(\n      x=sim_data_points$t, \n      y=sim_data_points$Cworm\n      ), \n    cex=3\n    )+\n  geom_label_repel(\n    aes(x=sim_data_points$t, \n        y=sim_data_points$Cworm, \n        label = sim_data_points$t\n        ),\n    box.padding   = 0.35, \n    point.padding = 0.5,\n    segment.color = Nord_polar[1]\n    )+\n  annotate(\n    \"text\", \n    x=t_elim/2, \n    y=min(sim_data_ex$Cworm), \n    colour=col_uptake, \n    label=\"Uptake\", \n    fontface=\"bold\"\n    )+\n  annotate(\n    \"text\", \n    x=t_elim*1.5, \n    y=max(sim_data_ex$Cworm), \n    colour=col_elim, \n    label=\"Elimination\", \n    fontface=\"bold\"\n    )+\n  \n  labs(x=\"Time (d)\", y=expression(paste(\"Concentration in earthworm\")))+\n  \n  theme_bw()+\n  theme(\n    legend.position = \"right\", \n    legend.title=element_text(size=sizetitle-2,face=\"bold\"), \n    title=element_text(size=sizetitle, face=\"bold\"), \n    axis.title.x = element_text(size=sizetitle,face=\"plain\"), \n    axis.title.y = element_text(size=sizetitle,face=\"plain\")\n    )\n\np\n```\n\n::: {.cell-output-display}\n![Design of the toxicokinetic experiments.](B0_TK_MM_files/figure-html/fig-TKdesign-1.png){#fig-TKdesign width=576}\n:::\n:::\n\n\n\n\n\n\n### Chemical analysis of soils and earthworms (HPLC-HRMS)\n\nAJOUTER PROTOCOLES\n\n### Relationship between fresh weight and fresh weight without gut content {#sec-RLW}\n\nSince experimental data include weights with and without gut content, we established a quantitative relationship between them to allow conversion and ensure consistency across datasets (@fig-Wfast).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_TK_full <- read_excel(here::here(\"data/Data_TK_long.xlsx\")) |> \n  filter(Experiment == \"TK\") |> \n  mutate(\n    Time_point_f = as.factor(Time_point),\n    ID = as.factor(ID),\n    w = w/1000, # Conversion mg to g\n    Dose = Dose*1000, # mg/kg to ng/g (mg/kg = microg/g = 1000 ng/g),\n    CiIMD = C_worm_IMD,\n    CiEPX = C_worm_EPX\n  ) |> \n  mutate(\n    C_soil_IMD = case_when(\n      t == 0 & ID_recipient == \"1\" ~ 0.089, # ng/g\n      t == 0 & ID_recipient == \"2\" ~ 0.072  # ng/g\n    ),\n    C_soil_EPX = case_when(\n      t == 0 & ID_recipient == \"1\" ~ 0.780, # ng/g\n      t == 0 & ID_recipient == \"2\" ~ 1.070  # ng/g\n    )\n  ) |> \n  mutate(expo = case_when(\n    Phase == \"Uptake\" ~ 1,\n    Phase == \"Elimination\" ~ 0,\n    Phase == \"Frozen\" ~ 2\n    )\n  ) |> \n  filter(Keep == \"Yes\" & Experiment == \"TK\") |> \n  group_by(ID) |> \n  mutate(t = as.numeric(difftime(Date, first(Date), units = \"days\"))) |> \n  dplyr::ungroup()\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# t1 = dernière masse avant expo == 2\nt1_df <- df_TK_full %>%\n  filter(Phase != \"Frozen\") %>%\n  group_by(ID) %>%\n  filter(t == max(t)) %>%\n  dplyr::select(ID, w_popo = w, Molecule)\n\n# t2 = première masse pendant expo == 2\nt2_df <- df_TK_full %>%\n  filter(Phase == \"Frozen\") %>%\n  group_by(ID) %>%\n  dplyr::select(ID, w_nopopo = w, Molecule)\n\n# Joindre les deux et calculer le pourcentage de perte\ndf_TK_fasting <- t1_df %>%\n  inner_join(t2_df, by = c(\"ID\", \"Molecule\")) %>%\n  mutate(\n    Per_loss = 100 * (w_popo - w_nopopo) / w_popo,\n    Loss = (w_popo - w_nopopo)\n    )\n\nlm.fasting <- lm(w_nopopo ~ w_popo+0, data = df_TK_fasting)\nsummary(lm.fasting)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = w_nopopo ~ w_popo + 0, data = df_TK_fasting)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.242005 -0.039962 -0.002733  0.031169  0.172331 \n\nCoefficients:\n       Estimate Std. Error t value Pr(>|t|)    \nw_popo 0.851127   0.006835   124.5   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.06364 on 124 degrees of freedom\nMultiple R-squared:  0.9921,\tAdjusted R-squared:  0.992 \nF-statistic: 1.551e+04 on 1 and 124 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n::: {.cell fig-label='fig-Wfast'}\n\n```{.r .cell-code}\ncoef_tmp <- as.numeric(signif(lm.fasting$coefficients[1],4))\n\ncol_reg <- Nord_polar[1]\n\np <- ggplot(\n  data = df_TK_fasting\n)+\n  geom_point(\n    aes(\n      x=w_popo,\n      y=w_nopopo,\n      color = Molecule\n      ),\n    alpha = 0.7\n  )+\n  geom_abline(\n    intercept = 0,\n    slope = lm.fasting$coefficients[1],\n    color = col_reg\n  )+\n  annotate(\n    geom = \"text\",\n    x = 0.7, y = 1.1,\n    label = as.expression(bquote(\n       bold(W[no~gut~content] == W[gut~content] %*% .(coef_tmp))\n    )),\n    color = col_reg,\n    size = 3.5,\n    parse = TRUE\n  )+\n  annotate(\n    geom = \"text\",\n    x = 0.7, y = 1,\n    label = as.expression(bquote(\n       bold(R^2 == .(signif(summary(lm.fasting)$r.squared, 4)))\n    )),\n    color = col_reg,\n    size = 3.5,\n    parse = TRUE\n  )+\n  scale_color_manual(values = col_Molecule)+\n  lims(x=c(0.4, 1.2), y=c(0.4, 1.2))+\n  labs(\n    x=\"Weight with gut content (g)\",\n    y=\"Weight without gut content (g)\"\n  )+\n  theme_minimal()\n\np\n```\n\n::: {.cell-output-display}\n![Relationship between fresh weight before and after fasting.](B0_TK_MM_files/figure-html/unnamed-chunk-5-1.png){width=480}\n:::\n:::\n\n\n\n\n\n\n### Dynamic of gut depuration in Petri dishes\n\nDepuration of the earthworm gut content was modeled as a first-order decay (@eq-GUT), informed by a small supporting experiment: ten earthworms were kept individually in 200 g of Closeaux soil with 3 g of horse dung for one week, then transferred to Petri dishes lined with moist filter paper and weighed at regular intervals. After 32 hours, the worms were gently massaged to void the remaining gut contents and weighed again, providing data to estimate the gut-clearance rate.\n\n$$\\frac{dP_{Weight}}{dt}=-\\frac{\\ln 2}{DT_{50,\\text{gut}}}\\ (P_{Weight}-P^{\\infty}_{Weight})$$ {#eq-GUT}\n\n$$P_{Weight}=P^{\\infty}_{Weight}+(100-P^{\\infty}_{Weight})\\ \\exp\\left(- \\frac{\\ln 2}{DT_{50,\\text{gut}}}\\times t\\right)$$\n\nWith :\n\n-   $t$ : Time (h)\n-   $P_{Weight}$ : Percentage of initial weight (%, 0-100)\n-   $P^{\\infty}_{Weight}$ : Percentage of initial weight when gut is fully emptied (%)\n-   $DT_{50,\\text{gut}}$ : Half-life of the gut content (h)\n\nFor the model, we consider that weights measured after massage are weights measured after a significant amount of time has passed. Therefore, the corresponding percentages of initial weight inform $P^{\\infty}_{Weight}$.\n\nThe results are shown @fig-GUTArticle.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_gut <- read_excel(here::here(\"data/Data_GUT.xlsx\")) |> \n  mutate(\n    ID = as.factor(ID)\n  ) |> \n  group_by(ID) |> \n  mutate(\n    Per_Weight = 100 * Weight / Weight[t == 0]\n    ) |> \n  ungroup() |> \n  mutate(Handling_plot = case_when(\n    Handling == \"Massaged\" ~ \"After complete gut\\nclearance (post-massage)\",\n    .default = \"During gut\\ndepuration phase\"\n  )) |> \n  mutate(Handling_plot = fct_relevel(Handling_plot, c(\"During gut\\ndepuration phase\", \"After complete gut\\nclearance (post-massage)\")))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_gut_mod <- df_gut |> \n  mutate(\n    t = case_when(\n      Handling == \"None\" ~ t,\n      Handling == \"Massaged\" ~ 1000\n    )\n  )\n\nmod.gut <- nlsLM(Per_Weight ~ Per_Weight_void + (100-Per_Weight_void)*exp(-lambda*t),\n               data = df_gut_mod,\n               start = list(\n                 Per_Weight_void = 15,\n                 lambda = 0.01\n                 ),\n               lower = c(0,0), \n               upper = c(Inf,Inf)\n               )\n\nsummary(mod.gut)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFormula: Per_Weight ~ Per_Weight_void + (100 - Per_Weight_void) * exp(-lambda * \n    t)\n\nParameters:\n                Estimate Std. Error t value Pr(>|t|)    \nPer_Weight_void 86.23468    0.82270 104.819  < 2e-16 ***\nlambda           0.15876    0.03239   4.902 2.62e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5.824 on 138 degrees of freedom\n\nNumber of iterations to convergence: 10 \nAchieved convergence tolerance: 1.49e-08\n```\n\n\n:::\n\n```{.r .cell-code}\n# cat(\"95% confidence intervals:\\n\") \nCI <- confint2(mod.gut, level = 0.95)\n\nDT50_gut_CI2.5 <- signif(as.numeric(log(2)/ CI[2,1]), 3)\nDT50_gut_CI97.5 <- signif(as.numeric(log(2)/ CI[2,2]), 3)\n\nPer_Weight_void_CI2.5 <- signif(CI[1,1], 3)\nPer_Weight_void_CI97.5 <- signif(CI[1,2], 3)\n\nDT50_gut <- signif(as.numeric(log(2)/ coef(mod.gut)[\"lambda\"]), 3)\nPer_Weight_void <- signif(as.numeric(coef(mod.gut)[\"Per_Weight_void\"]), 3)\n\ndf_gut_mod_plot <- df_gut_mod |> \n  filter(Handling == \"None\")\n\ndf_gut_mod_plot$Per_Weight_pred <- predict(mod.gut, newdata = df_gut_mod_plot)\n```\n:::\n\n\n\n\nThe estimated value for $DT_{50,\\text{gut}}$ and $P^{\\infty}_{Weight}$ are 4.37 \\[7.32 ; 3.11\\] hours and 86.2% \\[84.6 ; 87.9\\], respectively.\n\n$P^{\\infty}_{Weight}$ estimated here is consistent with the one estimated in @sec-RLW.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_mg <- ggplot(\n  data = df_gut, \n  aes(\n    x = t,\n    y = Weight,\n    group = ID,\n    shape = Handling_plot\n  )\n)+\n  geom_line(\n    color = Nord_polar[4],\n    linewidth = 0.8,\n    alpha = 0.8\n  )+\n  geom_point(\n    color = Nord_polar[1],\n    alpha = 0.5,\n    size = 2.5\n  )+\n  \n  labs(\n    x = \"Time (hours)\",\n    y = \"Weight (mg)\"\n  )+\n  scale_shape_manual(name = \"Handling\", values = shape_Molecule)+\n  theme_minimal()+\n  theme(\n    legend.spacing.y = unit(0.4, \"cm\"),\n    legend.text = element_text(lineheight = 1.1),\n    legend.key.height = unit(1, \"cm\"),\n    legend.title = element_text(face=\"bold\"),\n    legend.position = \"bottom\"\n  )\n\np_mod <- ggplot(\n  data = df_gut_mod_plot, \n  aes(\n    x = t,\n    y = Per_Weight,\n    group = ID\n  )\n)+\n  geom_line(\n    linewidth = 0.8,\n    alpha = 0.5,\n    color = Nord_polar[4]\n  )+\n  geom_point(\n    alpha = 0.5,\n    size = 2.5,\n    color = Nord_polar[1]\n  )+\n  geom_line(\n    data = df_gut_mod_plot, \n    aes(\n      x = t, \n      y = Per_Weight_pred\n    ),\n    linewidth = 2,\n    color = Nord_aurora[4],\n    alpha = 0.2\n  )+\n  \n  labs(\n    x = \"Time (hours)\",\n    y = \"Percentage of initial weight (%)\"\n  )+\n  theme_minimal()\n\np <- p_mg + p_mod + plot_layout(ncol=2, guides=\"collect\") &\n  theme(\n    legend.position = \"bottom\"\n  )\np\n```\n\n::: {.cell-output-display}\n![Evolution of earthworm weight and the corresponding percentage of initial weight throughout time in Petri dishes. Weight after being massaged are described with squared points.](B0_TK_MM_files/figure-html/fig-GUTArticle-1.png){#fig-GUTArticle width=768}\n:::\n:::\n\n\n\n\n\n\n## Toxicokinetics modeling\n\nTwo toxicokinetic model structures were tested to describe the dynamics of internal pesticide concentrations in earthworms: a one-compartment and a two-compartment model. The two-compartment structure was considered to account for potential differential distribution of compounds within the organism, particularly for epoxiconazole, a lipophilic substance that may partition into lipid-rich tissues. For consistency and comparability between compounds, the same two-compartment structure was also applied to imidacloprid. The one- and two-compartment models are hereafter referred to as “C1” and “C2”, respectively. Both model structures explicitly account for growth dilution.\n\nIn addition, two exposure scenarios were tested to account for the depuration phase prior to chemical analysis. Before freezing, earthworms were transferred to Petri dishes lined with moist filter paper for approximately 24 hours to allow gut clearance and avoid measuring soil residues in the digestive tract. During this period, worms were no longer in direct contact with contaminated soil; however, residual exposure could still occur through ingestion of contaminated soil particles retained in the gut. To evaluate the influence of this potential pathway, two alternative exposure scenarios were implemented, differing in whether uptake was assumed to continue during the depuration phase.\n\nIn each model, the internal contaminant concentration ($C_{\\text{int}}$) is then modeled by a differential equation integrating three processes: (i) uptake from soil, which is proportional to $C_{\\text{ext}}$ via the uptake rate constant ($k_u$); (ii) elimination from the organism, which follows first-order kinetics with rate constant ($k_e$); and (iii) growth dilution, expressed as a term proportional to the growth rate and the current internal concentration. This last process reduces the concentration, reflecting the increase in biomass. All state variables and parameters are listed @tbl-Variables.\n\n### One compartment model\n\nIn the one-compartment model (C1), the internal concentration ($C_{\\text{int}}$) changes over time as a balance between uptake from soil ($C_{\\text{ext}}$), elimination to the external medium, and dilution by growth (@eq-TKsimple). Because individual body weights were available throughout the experiment, a hierarchical model for growth was implemented on the same principle as in @gollot_2025. This dynamic is governed by @eq-TKC1.\n\n$$\\frac{dC_{\\text{int}}}{dt} =  (k_u\\ C_{\\text{ext}}-k_e\\ C_{\\text{int}})-\\frac 1 V \\frac{dV}{dt}C_{\\text{int}}$$ {#eq-TKsimple}\n\n$$\\frac{dC_{int}}{dt} = (k_u\\ C_{ext}-k_e\\ C_{int})-\\frac{3a}{L}C_{int}, \\ \\ \\text{ with}\\ \\  C_{int}(t=0) = C_{int}^0$$ {#eq-TKC1}\n\nWhere $k_u$ and $k_e$ are the uptake and elimination rates of the contaminant by the earthworm, $L$ is the structural length of the earthworm, and $a_i$ the individual growth rate.\n\n### Two-compartment model\n\nIn the two-compartment model (C2) model, the earthworm body is considered as consisting of a central compartment (e.g., blood or well-perfused tissues) and a peripheral compartment (e.g., storage or poorly perfused tissues), with bidirectional exchanges between them ($k_{periph}$). Uptake from soil occurs only into the central compartment, from which the substance can either be eliminated to the external medium or distributed to the peripheral compartment. The peripheral compartment acts as a storage site that can delay elimination and buffer fluctuations in exposure, which is particularly relevant for hydrophobic compounds expected to partition into lipid-rich tissues. Such a structure allows us to account for a biphasic accumulation and elimination pattern, typically characterized by a fast initial phase driven by the central compartment and a slower phase reflecting the exchange with the peripheral compartment. The internal concentration is now described by @eq-2comp, where the dynamics of the central and peripheral compartments are jointly expressed, enabling a more mechanistic representation of toxicokinetics for lipophilic pesticides in earthworms.\n\n$$\n\\begin{aligned}\n& C_{\\text{int},\\mu} = C_{\\text{int,central},\\mu} + C_{\\text{int,periph},\\mu}\\\\ \\\\\n&\\frac{dC_{\\text{int,central},\\mu}}{dt} =  (k_u\\ C_{\\text{ext}}-k_e\\ C_{\\text{int,central},\\mu}+k_{periph}\\ C_{\\text{int,periph},\\mu}-k_{periph}\\ C_{\\text{int,central},\\mu})-\\frac{3a_i}{L_{i,\\mu}}C_{\\text{int,central},\\mu}, \\\\ \n&\\text{ with}\\ \\  C_{\\text{int,central},\\mu}(t=0) = \\frac 1 2 C_{\\text{int},\\mu}^0\\\\ \\\\\n&\\frac{dC_{\\text{int,periph},\\mu}}{dt} =  (k_{periph}\\ C_{\\text{int,central},\\mu}-k_{periph}\\ C_{\\text{int,periph},\\mu})-\\frac{3a_i}{L_{i,\\mu}}C_{\\text{int,periph},\\mu}, \\\\ \n&\\text{ with}\\ \\  C_{\\text{int,periph},\\mu}(t=0) = \\frac 1 2 C_{\\text{int},\\mu}^0\n\\end{aligned}\n$$ {#eq-2comp}\n\n### Chemical fate\n\nThe external contaminant concentration in soil ($C_{\\text{ext}}$) is described by first-order dissipation, parameterized by the pesticide-specific half-life (DT$_{50}$) (@eq-Cext). For epoxiconazole (EPX) and imidacloprid (IMD), the DT$_{50}$ values are 353.3 and 187 days, respectively. The initial concentration corresponds to the spiked soil, which decreases over time following first-order kinetics, and after 21 days is set equal to the residual concentration measured in natural soil. For the phase when earthworm are put on wet filter paper in Petri dishes for depuration, by default, we consider that no exposure occurs and therefore $C_{\\text{ext}}$ is set to zero.\n\n$$\n\\begin{align}\n&\\frac{dC_{ext}}{dt} = -\\frac{\\ln 2}{DT_{50}}\\ C_{ext}, \\ \\ \\text{ with}\n\\begin{cases}\nC_{ext}(t=0) = C_{ext}^0\\\\\nC_{ext}(t=21 \\text{ days)} = C_{Clx}^0\n\\end{cases}\n\\end{align}\n$$ {#eq-Cext}\n\n### Exposure scenario : Exposure through gut content while in Petri dishes ?\n\nTo account for potential residual exposure during the depuration phase, we tested two alternative exposure scenarios : (i) no exposure occurring in Petri dishes and (ii) assuming a digestive contribution of % of the total uptake when earthworms are in Petri dishes with contaminated soil still in their gut content (models noted with a “P”).\n\nTo evaluate the influence of the depuration phase on toxicokinetic parameter estimation, different approaches were implemented depending on the compound. For imidacloprid, a reduced two-compartment model (C2N) was developed by assuming no net exchange during the depuration phase (uptake and elimination rates set to zero), and its performance was compared to the C2 model using the Bayesian Information Criterion (BIC). For epoxiconazole, the impact of the depuration phase was assessed by comparing the bioaccumulation factor estimated from the TK model with the steady-state BAF (BAF$_{ss}$) calculated directly from measured concentrations after depuration, following OECD TG 317. This approach allowed us to quantify the bias introduced by neglecting the depuration phase for compounds with rapid toxicokinetics.\n\n| Symbol | Code Symbol | Description | Unit |\n|----|----|----|----|\n| $W$ | `Weight` | Weight of the earthworm without gut content | g(worm) |\n| $L$ | `L` | Volumetric length of the earthworm | g<sup>1/3</sup>(worm) |\n| $L_0$ | `L0` | Volumetric length of the earthworm at the start of the experiment | g<sup>1/3</sup>(worm) |\n| $a$ | `a_growth` | Growth rate of the earthworm in soil | g<sup>1/3</sup>(worm)·d⁻¹ |\n| $C_{\\text{ext}}$ | `CeEPX` or `CeIMD` | Soil concentration of contaminant | ng·g(soil)⁻¹ |\n| $C_{\\text{ext}}^{0}$ | `Ce0EPX` or `Ce0IMD` | Soil concentration of contaminant at the start of the experiment | ng·g(soil)⁻¹ |\n| $C_{\\text{clx}}^0$ | `Cclx0` | Natural soil concentration in contaminant | ng·g(soil)⁻¹ |\n| $DT_{50}$ | `DT50EPX` or `DT50IMD` | Half-life of the contaminant in soil | d⁻¹ |\n| $DT_{50,\\text{depuration}}$ | `DT50gut` | Half-life of the gut content in Petri dishes | d⁻¹ |\n| $\\varphi$ | `phi` | Fraction of the uptake that is due to gut content | – |\n| $C_{\\text{int}}$ | `CiEPX` or `CiIMD` | Concentration of contaminant in earthworm | ng·g(worm)⁻¹ |\n| $C_{\\text{int}}^0$ | `Ci0EPX` or `Ci0IMD` | Concentration of contaminant in earthworm at the start of the experiment | ng·g(worm)⁻¹ |\n| $k_u$ | `ku` | Uptake rate of the contaminant by earthworm from soil | g(soil)·g(worm)⁻¹·d⁻¹ |\n| $k_e$ | `ke` | Elimination rate of the contaminant by earthworm | d⁻¹ |\n\n: State variables and parameters list. {#tbl-Variables}\n\n### Model parametrization and calibration\n\nThe linear model fitted to paired measurements of earthworm body weight with and without gut content indicated that gut content represents approximately 15% of fresh weight ($W_{\\text{without  gut content}}=0.85  \\times W_{\\text{with gut content}},\\ R^2= 0.992$, @sec-RLW), and was subsequently used to convert measurements with gut content into gut-free body weight for consistency across datasets.\n\nThen, the structural length of the earthworm ($L=V^{1/3}$) is related to the weight without gut content ($W$) through an allometric relationship with a 1/3 power scaling. Both internal concentration and individual weight are assumed to follow probability distributions, with internal concentration following a log-normal distribution of a mean $C_{\\text{int},\\mu}$, and a variance $C_{\\text{int},\\sigma}$, and weight normally distributed around a mean, $W_{\\mu}$, with a specified standard deviation, $W_{\\sigma}$, (@eq-distrib).\n\n$$\n\\begin{align}\nW_{i,\\mu} &= L_{i,\\mu}^{3}\\\\\nW_i &\\sim \\mathcal N (W_{i,\\mu},W_{\\sigma})\\\\\nC_{\\text{int},i} &\\sim \\text{log-}\\mathcal N (C_{\\text{int},\\mu},C_{\\text{int},\\sigma})\\\\\na_i &\\sim \\mathcal N (a_{i,\\mu},a_{i,\\sigma})\\\\\n\\end{align}\n$$ {#eq-distrib}\n\nGrowth in soil is described by a growth rate parameter drawn from a normal distribution, which is set to zero during fasting phases in Petri dishes, where no growth is assumed (@eq-growth) [@gollot_2025].\n\n$$\n\\begin{align}\n\\frac{dL_{i,\\mu}}{dt}\n  &= \\begin{cases}\n       a_i, & \\text{if in soil}\\\\\n       0,   & \\text{if in Petri dishes}\n     \\end{cases}\n  & & \\text{with } L_i(0) = L_{0,i} \\\\[1ex]\n\\end{align}\n$$ {#eq-growth}\n\nModel calibration was performed with a bayesian inference software, MCSim, using 3 chains and 100,000 iterations. Parameter values were inferred by Bayesian numerical calibration [@bois_2009]. Other statistical analyses were performed using the software R. Large and weakly informative priors were assigned to the toxicokinetic rate constants in order to cover a wide range of plausible values. Specifically, the uptake ($k_u$), elimination ($k_e$), and inter-compartmental exchange rates ($k_{periph}$) were given large log-uniform priors, ensuring that the posterior estimates would be primarily informed by the data rather than overly restrictive assumptions. For the growth process, truncated normal priors were specified for both the mean growth rate and its inter-individual variation, reflecting prior biological knowledge of adult earthworm growth while avoiding unrealistic values.\n\nMeasurement processes were also integrated in the model: observed body weights were assigned truncated normal distributions to ensure positivity and consistency with biological constraints, while internal concentrations were assumed to follow truncated log-normal distributions, which guarantee non-negative values. Posterior distributions were drawn using the last 10,000 iterations of each chain. BAFK were calculated as the ratio between ku and ke, using the last 10,000 iterations from each MCMC chain. Model comparison was based on the Bayesian Information Criterion (BIC), which balances goodness-of-fit and model complexity by penalizing models with a higher number of parameters.\n\nA total of three individuals were excluded as outliers prior to data analysis: two earthworms at the 35-day time point for epoxiconazole and one earthworm at the 17-day time point for imidacloprid. Their internal concentrations were markedly inconsistent with both model predictions and co-sampled replicates, deviating by approximately 100-fold and 8-fold, respectively, suggesting potential analytical or sampling artefacts\n\nThe @sec-ModIMDBIS and @sec-ModEPXBIS sections present the fit of the different model on the full data set (TK & TK BIS). The @sec-ModIMD and @sec-ModEPX sections present what would have happened if we did not performed the TK BIS experiment.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}